config/routes.rb
Rails.application.routes.draw do
  get 'hospitals/edit'

  get 'staffs/index'

  get 'staffs/new'

  get 'staffs/create'

  get 'staffs/edit'

  get 'staffs/update'

  get 'staffs/destroy'

  get 'staffs/show'

  root 'hospitals#index'
  resources :hospitals
  resources :staffs
  get 'hospitals/update'
  get 'hospitals/index'

  get 'hospitals/create'

  get 'hospitals/show'

  get 'hospitals/destroy'
  get 'hospitals/new'

  get 'hospitals/:id/staffs/:staff_id', to: 'hospitals#lay_off', as: :layoff
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hospital.rb
class Hospital < ApplicationRecord
  validates :num, presence: true, numericality: { only_integer: true ,greater_than: 0}, uniqueness: true

  has_and_belongs_to_many :staffs
end

app/models/staff.rb
class Staff < ApplicationRecord
  validates :sname, presence: true, length: { minimum: 2, maximum: 15}
  validates :bday, presence:true, format: { with: /(\d{4})\-(0\d|1[012])\-([0-2]\d|3[01])/}
  validates :position, presence:true, inclusion: { in: %w(Doctor Nurse Paramedic)}

  has_and_belongs_to_many :hospitals


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/hospitals_controller.rb
class HospitalsController < ApplicationController
  def index
    @hospitals = Hospital.all
  end

  def create
    @hospital = Hospital.new(hospital_params)
    staff_ids = params[:hospitals_staffs]
    if @hospital.save
        if staff_ids != nil
            staff_ids.each do |staff_id|
            @hospital.staffs << Staff.find_by(id:staff_id)
            flash[:notice] = "Больница создана"
            redirect_to root_path
            end
          else
        flash[:notice] = "Больница создана"
        redirect_to root_path
        end
    else
      flash[:alert] = @hospital.errors.full_messages
      redirect_to hospitals_new_path
    end
  end

  def show
    @hospital = Hospital.find(params[:id])
    @staffs = @hospital.staffs
  end

  def destroy

    @hospital = Hospital.find(params[:id])
    @hospital.destroy
    flash[:notice] = "Больница удалена "
    redirect_to root_path
  end

  def new
  @page_title = 'Добавление больницы'
  @hospital = Hospital.new
  @staffs = Staff.all
  end

  def lay_off
    @hospital = Hospital.find(params[:id])
    @hospital.staffs.delete(Staff.find(params[:staff_id]))
    @hospital.reload
    flash[:notice] = "Сотрудник исключен из больницы"
    redirect_back(fallback_location: root_path)
  end

  def update
    @hospital = Hospital.find(params[:id])
    staff_ids = params[:hospitals_staffs]
    if @hospital.update(hospital_params)
      if staff_ids != nil
      staff_ids.each do |staff_id|
        @hospital.staffs << Staff.find_by(id:staff_id)
        flash[:notice] = "Больница добавлена"
        redirect_to hospital_path(@hospital)
      end
      else
      flash[:notice] = "Больница добавлена"
      redirect_to hospital_path(@hospital)
      end
    else
      flash[:alert] = @hospital.errors.full_messages
      redirect_to edit_hospital_path(@hospital)
    end
  end

  def edit
    @hospital = Hospital.find(params[:id])
    @staffs = Staff.all - @hospital.staffs
  end



  private

  def hospital_params
    params.require(:hospital).permit(:num)
  end
end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  def index
    @staffs = Staff.all
  end

  def new
    @page_title = "Добавление сотрудника"
    @staff = Staff.new
    @hospitals = Hospital.all
  end



  def create
    @staff = Staff.new(staff_params)
    hospital_ids = params[:hospitals_staffs]
    if @staff.save
      if hospital_ids != nil
      hospital_ids.each do |hospital_id|
        @staff.hospitals << Hospital.find_by(id:hospital_id)
        flash[:notice] = "Сотрудник добавлен"
        redirect_to staffs_index_path
      end
      else
      flash[:notice] = "Сотрудник добавлен"
      redirect_to staffs_index_path
      end

    else
      flash[:alert] = @staff.errors.full_messages
      redirect_to staffs_new_path
    end

  end

  def destroy
    @staff = Staff.find(params[:id])
    @staff.destroy
    flash[:notice] = "Сотрудник удален"
    redirect_to staffs_index_path
  end

  def edit
    @staff = Staff.find(params[:id])
    @hospitals = Hospital.all - @staff.hospitals

  end

  def update
    @staff = Staff.find(params[:id])
    hospital_ids = params[:hospitals_staffs]
    if @staff.update(staff_params)
      if hospital_ids != nil
        hospital_ids.each do |hospital_id|
          @staff.hospitals << Hospital.find_by(id:hospital_id)
          flash[:notice] = "Информация изменена"
          redirect_to staffs_index_path
          end
        else
      flash[:notice] = "Информация о сотруднике изменена"
      redirect_to staff_path(@staff)
      end
    else
      flash[:alert] = @staff.errors.full_messages
      redirect_to edit_staff_path
      end


  end

  def show
    @staff = Staff.find(params[:id])
    @hospitals = @staff.hospitals
  end
  private

  def staff_params
      params.require(:staff).permit(:sname, :bday, :position)

    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hospitals_helper.rb
module HospitalsHelper
end

app/helpers/staff_helper.rb
module StaffHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/views/hospitals/edit.html.erb
<div class="container">
<h1>Изменение информации о больнице</h1>
<%=form_for @hospital do |f| %>

  <div class="form-group">
    <%= f.label :text ,"Номер Больнинцы" %>
    <%= f.number_field :num, class: 'form-control' %>
  </div>
  <br />
  <div class="form-group">

    <h3>Добавить сотрудника</h3>
    <% @staffs.each_slice(5) do |staff| %>
      <div class="row">
        <% staff.each do |staff| %>
          <div class="col-md-2 col-sm-3" >
            <div class="card">
              <h4><%= staff.position %></h4>
              <h1><%= staff.sname %></h1>
              <h5>Дата рождения: <%= staff.bday %></h5>
              <%= check_box_tag "hospitals_staffs[]", staff.id %>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
  <%= f.submit "Сохранить", class:'btn btn-primary' %>
  <%= link_to 'Закрыть', hospital_path(@hospital), class:'btn btn-danger' %>

<% end %>

</div>

app/views/hospitals/index.html.erb
<nav class="navbar navbar-expand-md navbar-light" style="background-color: #e3f2fd;">
  <%= link_to 'Добавить больницу', hospitals_new_path, class: "nav-link" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
</nav>
<div class="container">
  <% @hospitals.each_slice(@hospitals.length+1) do |hospital| %>
    <div class="row">
      <% hospital.each do |hospital| %>
        <div class="col-md-2 col-sm-3" >
          <div class="card">
            <h5>Больница №</h5>
              <h1><%= hospital.num %></h1>
              <%= link_to 'Подробнее', hospital_path(hospital), class: 'btn btn-primary' %>
              <%= button_to "Удалить", hospital_path(hospital), :method => "delete",
                            class: 'btn btn-danger' %>
            </div>
          </div>

    <% end %>

      </div>
    <% end %>


  </div>

app/views/hospitals/new.html.erb
<h1>Добавление новой больницы</h1>
<div class="container">

<%=form_for @hospital do |f| %>

  <div class="form-group">
    <%= f.label :text ,"Номер Больнинцы" %>
    <%= f.number_field :num, class: 'form-control' %>
  </div>
  <br />
  <div class="form-group">
    <h3>Отметьте персонал больницы</h3>
    <% @staffs.each_slice(5) do |staff| %>
      <div class="row">
        <% staff.each do |staff| %>
          <div class="col-md-2 col-sm-3" >
            <div class="card">
              <h4><%= staff.position %></h4>
              <h1><%= staff.sname %></h1>
              <h5>Дата рождения: <%= staff.bday %></h5>
              <%= check_box_tag "hospitals_staffs[]", staff.id %>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
  <%= f.submit "Сохранить", class:'btn btn-primary' %>
  <%= link_to 'Закрыть', root_path, class:'btn btn-danger' %>

<% end %>
</div>

app/views/hospitals/show.html.erb
<div class="container">
<h1>Больница № <%= @hospital.num %></h1> <br />
<h3>Персонал:</h3><br />
  <% @staffs.each_slice(5) do |staff| %>
    <div class="row">
      <% staff.each do |staff| %>
        <div class="col-md-2 col-sm-3" >
          <div class="card">
            <h4><%= staff.position %></h4>
            <h1><%= staff.sname %></h1>
            <h5>Дата рождения: <%= staff.bday %></h5>
            <%= link_to 'Подробнее', staff_path(staff), class: 'btn btn-primary' %>
            <%= link_to 'Исключить', layoff_path(@hospital.id, staff.id), class: 'btn btn-danger' %>

          </div>
        </div>
      <% end %>
    </div>
  <% end %>
<%= link_to 'Редактировать', edit_hospital_path, class: 'btn btn-primary'  %>
<%= button_to "Удалить", @hospital, :method => "delete" ,class: 'btn btn-danger'%>

  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title %></title>
    <%= csrf_meta_tags %>
    <meta charset="UTF-8">
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <%= link_to 'HOSPdb', root_path, class: "nav-link" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item dropdown">
        <li class="nav-item active">
          <%= link_to 'Больницы', hospitals_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
        <%= link_to 'Персонал', staffs_path, class: "nav-link" %>
        </li>
      </ul>

    </div>
  </nav>
  <div class="content">
    <% if flash[:notice] %>
      <div class="alert alert-success"><%= flash[:notice] %></div>
    <% end %>

    <% if flash[:alert] %>
      <div class="alert alert-danger"><%= flash[:alert] %></div>
    <% end %>
  <%= yield %>
  </div>



  </body>
</html>

app/views/staffs/create.html.erb
<h1>Staffs#create</h1>
<p>Find me in app/views/staffs/create.html.erb</p>

app/views/staffs/destroy.html.erb
<h1>Staffs#destroy</h1>
<p>Find me in app/views/staffs/destroy.html.erb</p>

app/views/staffs/edit.html.erb
<div class="container">
<h1><%= @staff.sname+' '+@staff.bday %></h1>

<%=form_for @staff do |f| %>
  <div class="form-group">
    <%= f.label :text ,"Фамилия" %>
    <%= f.text_field :sname, class: 'form-control' %>
  </div>
  <br />
  <div class="form-group">
    <%= f.label :text ,"Дата рождения" %>
    <br />
    <%= date_field(:staff, :bday, value:@staff.bday) %>
  </div>
  <br />
  <div class="form-group">
    <%= f.label :position ,"Должность" %>
    <%= select(:staff, :position,%w(Doctor Nurse Paramedic)) %>
  </div>
  <div class="form-group">
    <% @hospitals.each_slice(@hospitals.length+1) do |hospital| %>
      <div class="row">
        <% hospital.each do |hospital| %>
          <div class="col-md-2 col-sm-3" >
            <div class="card">
              <h5>Больница №</h5>
              <h1><%= hospital.num %></h1>
              <%= check_box_tag "hospitals_staffs[]", hospital.id %>
            </div>
          </div>

        <% end %>

      </div>
    <% end %>
  </div>
  <%= f.submit "Сохранить", class:'btn btn-primary' %>
  <%= link_to 'Закрыть', staff_path(@staff), class:'btn btn-danger' %>

<% end %>

</div>

app/views/staffs/index.html.erb
<nav class="navbar navbar-expand-md navbar-light" style="background-color: #e3f2fd;">
  <%= link_to 'Добавить сотрудника', staffs_new_path, class: "nav-link" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
</nav>
<div class="container">
  <% @staffs.each_slice(@staffs.length+1) do |staff| %>
    <div class="row">
      <% staff.each do |staff| %>
        <div class="col-md-2 col-sm-3" >
          <div class="card">
            <h4><%= staff.position %></h4>
            <h1><%= staff.sname %></h1>
            <h5>Дата рождения: <%= staff.bday %></h5>
            <%= link_to 'Подробнее', staff_path(staff), class: 'btn btn-primary' %>
            <%= button_to "Удалить", staff_path(staff), :method => "delete",
                          class: 'btn btn-danger' %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>


</div>
</div>

app/views/staffs/new.html.erb
<div class="container">
  <h1>Добавление нового сотрудника</h1>
  <%=form_for @staff do |f| %>
    <div class="form-group">
      <%= f.label :text ,"Фамилия" %>
      <%= f.text_field :sname, class: 'form-control' %>
    </div>
    <br />
    <div class="form-group">
      <%= f.label :text ,"Дата рождения" %>
      <br />
      <%= date_field(:staff, :bday) %>
    </div>
    <br />
    <div class="form-group">
      <%= f.label :position ,"Должность" %>
      <%= select(:staff, :position,%w(Doctor Nurse Paramedic)) %>
    </div>
    <p>
      <% for hospital in Hospital.all %>
      <div>
        <%= check_box_tag "staff[hospital_ids][]", hospital.id, @staff.hospitals.include?(hospital) %>
        <%= hospital.num %>
      </div>
      <% end %>
    </p>

    <div class="form-group">
      <% @hospitals.each_slice(@hospitals.length) do |hospital| %>
        <div class="row">
          <% hospital.each do |hospital| %>
            <div class="col-md-2 col-sm-3" >
              <div class="card">
                <h5>Больница №</h5>
                <h1><%= hospital.num %></h1>
                <%= check_box_tag "hospitals_staffs[]", hospital.id %>
              </div>
            </div>

          <% end %>

        </div>
      <% end %>
    </div>
    <%= f.submit "Сохранить", class:'btn btn-primary' %>
    <%= link_to 'Закрыть', root_path, class:'btn btn-danger' %>

  <% end %>

</div>

app/views/staffs/show.html.erb
<div class="container">
<h1><%= @staff.sname %></h1>
<h3>Дата рождения: <%= @staff.bday %></h3>
<h2><%= @staff.position %></h2>
<h3>Сотрудник следующих больниц</h3>
  <% @hospitals.each_slice(5) do |hospital| %>
    <div class="row">
      <% hospital.each do |hospital| %>
        <div class="col-md-2 col-sm-3" >
          <div class="card">
            <h5>Больница №</h5>
            <h1><%= hospital.num %></h1>
            <%= link_to 'Покинуть', layoff_path(hospital.id, @staff.id), class: 'btn btn-danger' %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>

<%= link_to "Редактировать", edit_staff_path, class: 'btn btn-primary' %>
<%= button_to "Удалить", @staff, :method => "delete",
              class: 'btn btn-danger' %>


</div>

app/views/staffs/update.html.erb
<h1>Staffs#update</h1>
<p>Find me in app/views/staffs/update.html.erb</p>